#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const {readVersion} = require('./read-version');

const root = path.resolve(__dirname, '..');

function updateJson (relPath, version) {
	const filePath = path.join(root, relPath);
	const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

	if (data.version === version) {
		return false;
	}

	data.version = version;
	fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n');
	return true;
}

function syncPackageLock (version) {
	const filePath = path.join(root, 'package-lock.json');
	const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
	let changed = false;

	if (data.version !== version) {
		data.version = version;
		changed = true;
	}

	if (data.packages?.['']?.version !== version) {
		data.packages[''].version = version;
		changed = true;
	}

	if (changed) {
		fs.writeFileSync(filePath, JSON.stringify(data, null, '\t') + '\n');
	}

	return changed;
}

const version = readVersion();

for (const relPath of ['package.json', 'webos-meta/appinfo.json', 'services/package.json']) {
	if (updateJson(relPath, version)) {
		console.log(`sync-version: ${relPath} -> ${version}`);
	}
}

if (syncPackageLock(version)) {
	console.log(`sync-version: package-lock.json -> ${version}`);
}

function syncAppVersion (version) {
	const filePath = path.join(root, 'src', 'version.js');
	const next = `// Generated by scripts/sync-version.js — do not edit.\nexport const VERSION = '${version}';\n`;
	const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';

	if (prev === next) {
		return false;
	}

	fs.writeFileSync(filePath, next);
	return true;
}

if (syncAppVersion(version)) {
	console.log(`sync-version: src/version.js -> ${version}`);
}